def get_dict():
    """Return the questions and answers"""
    # Here is where you may enter in questions and answers.
    question_list = ["Which sport is known as 'the beautiful game'?",
                     "Which country hosts the annual Formula One race known as the Monaco Grand Prix?",
                     "In tennis, what term is used for a score of zero?",
                     "Who is known as 'The Great One' in ice hockey?",
                     "In golf, what is the term for one stroke under par on a hole?",
                     "Who played Jack in the movie 'Titanic'?",
                     "What is the name of the kingdom where the 2013 movie 'Frozen' is set?",
                     "What is the famous line from 'Jaws' when Chief Brody sees the great white shark for the first time?",
                     "In which movie does Tom Hanks play a character stranded on a deserted island with a volleyball named Wilson?",
                     "In 'The Wizard of Oz,' what does Dorothy say to go back to Kansas?",
                     "Which British band sang 'Hey Jude'?",
                     "What is Elvis Presley's middle name?",
                     "Who is known as the 'Queen of Pop'?",
                     "In which city was Ludwig van Beethoven born?",
                     "What is the name of the music festival held annually in California's Coachella Valley?",
                     "Which country is known as the Land of the Rising Sun?",
                     "In which country would you find the Sydney Opera House?",
                     "Which U.S. state is known as the 'Sunshine State'?",
                     "What is the capital city of Spain?",
                     "What is the name of the world's highest mountain?",
                     "In what year did the Titanic sink?",
                     "Which famous wall was built in the north of England by the Romans?",
                     "During which war was the Battle of Gettysburg fought?",
                     "Who was the British Prime Minister during most of World War II?",
                     "In which year did the Berlin Wall fall?",
                     "What is the chemical symbol for water?",
                     "Which is the largest mammal in the world?",
                     "In the periodic table, what is the symbol for gold?",
                     "What is the boiling point of water in degrees Celsius?",
                     "What kind of animal is a Komodo dragon?",
                     "What type of pasta's name means 'little worms'?",
                     "Champagne is a sparkling wine from a region in which country?",
                     "Which fruit is known as the 'king of fruits' and is notorious for its strong smell?",
                     "What is the main ingredient in traditional Italian pesto sauce?",
                     "What is the primary ingredient used to make the Indian flatbread 'naan'?",
                     "What is the title of the first book in the 'Game of Thrones' series by George R.R. Martin?",
                     "In which novel would you find the characters Elizabeth Bennet and Mr. Darcy?",
                     "Who is the famous author of 'The Great Gatsby'?",
                     "What is the name of the fictional detective created by Sir Arthur Conan Doyle?",
                     "What is the main color of the iconic jacket worn by Holden Caulfield in 'The Catcher in the Rye'?",
                     "How many hearts do octopus have?",
                     "What is the well-known irrational number used to calculate measurements of a circle?",
                     "What element made the WWI zeppelins fly?",
                     "From which country was the assassin of Archduke Franz Ferdinand?",
                     "What must be done to food in order for it to have flavor?",
                     "How many feet are in 1 mile?"]

    q_and_a_dict = {"Which sport is known as 'the beautiful game'?": "Soccer",
                    "Which country hosts the annual Formula One race known as the Monaco Grand Prix?": "Monaco",
                    "In tennis, what term is used for a score of zero?": "Love",
                    "Who is known as 'The Great One' in ice hockey?": "Wayne Gretzky",
                    "In golf, what is the term for one stroke under par on a hole?": "Birdie",
                    "Who played Jack in the movie 'Titanic'?": "Leonardo DiCaprio",
                    "What is the name of the kingdom where the 2013 movie 'Frozen' is set?": "Arendelle",
                    "What is the famous line from 'Jaws' when Chief Brody sees the great white shark for the first time?": "You're gonna need a bigger boat",
                    "In which movie does Tom Hanks play a character stranded on a deserted island with a volleyball named Wilson?": "Cast Away" or "castaway",
                    "In 'The Wizard of Oz,' what does Dorothy say to go back to Kansas?": "There's no place like home",
                    "Which British band sang 'Hey Jude'?": "The Beatles",
                    "What is Elvis Presley's middle name?": "Aaron",
                    "Who is known as the 'Queen of Pop'?": "Madonna",
                    "In which city was Ludwig van Beethoven born?": "Bonn",
                    "What is the name of the music festival held annually in California's Coachella Valley?": "Coachella Valley Music and Arts Festival",
                    "Which country is known as the Land of the Rising Sun?": "Japan",
                    "In which country would you find the Sydney Opera House?": "Australia",
                    "Which U.S. state is known as the 'Sunshine State'?": "Florida",
                    "What is the capital city of Spain?": "Madrid",
                    "What is the name of the world's highest mountain?": "Mount Everest",
                    "In what year did the Titanic sink?": "1912",
                    "Which famous wall was built in the north of England by the Romans?": "Hadrian's Wall",
                    "During which war was the Battle of Gettysburg fought?": "The American Civil War",
                    "Who was the British Prime Minister during most of World War II?": "Winston Churchill",
                    "In which year did the Berlin Wall fall?": "1989",
                    "What is the chemical symbol for water?": "H2O",
                    "Which is the largest mammal in the world?": "Blue Whale",
                    "In the periodic table, what is the symbol for gold?": "Au",
                    "What is the boiling point of water in degrees Celsius?": "100 degrees" or "100",
                    "What kind of animal is a Komodo dragon?": "Lizard",
                    "What type of pasta's name means 'little worms'?": "Vermicelli",
                    "Champagne is a sparkling wine from a region in which country?": "France",
                    "Which fruit is known as the 'king of fruits' and is notorious for its strong smell?": "Durian",
                    "What is the main ingredient in traditional Italian pesto sauce?": "Basil",
                    "What is the primary ingredient used to make the Indian flatbread 'naan'?": "Flour",
                    "What is the title of the first book in the 'Game of Thrones' series by George R.R. Martin?": "A Game of Thrones",
                    "In which novel would you find the characters Elizabeth Bennet and Mr. Darcy?": "Pride and Prejudice",
                    "Who is the famous author of 'The Great Gatsby'?": "F. Scott Fitzgerald",
                    "What is the name of the fictional detective created by Sir Arthur Conan Doyle?": "Sherlock Holmes",
                    "What is the main color of the iconic jacket worn by Holden Caulfield in 'The Catcher in the Rye'?": "Red",
                    "How many hearts do octopus have?": "three" or "3",
                    "What is the well-known irrational number used to calculate measurements of a circle?": "pi",
                    "What element made the WWI zeppelins fly?": "Hydrogen",
                    "From which country was the assassin of Archduke Franz Ferdinand?": "Serbia",
                    "What must be done to food in order for it to have flavor?": "Dissolving" or "Dissolve",
                    "How many feet are in 1 mile?": "5280"}
    return question_list, q_and_a_dict
